<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Depo</name>
   <tag></tag>
   <elementGuidId>e7a8f607-cf1d-425b-b643-e732069cdd61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#management-ajudan-depo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='management-ajudan-depo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>056a1fe8-faa0-4e1d-b96a-037071b6eefc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sublevel-nav-link ng-tns-c115-67 ng-star-inserted</value>
      <webElementGuid>eb718e25-4f85-41a8-9371-dcffc07bf5cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>management-ajudan-depo</value>
      <webElementGuid>a24d3907-53e2-4b23-a94a-e9a2c17a3069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Depo</value>
      <webElementGuid>7e18d507-e134-40bd-bfd5-dffaebd457f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;management-ajudan-depo&quot;)</value>
      <webElementGuid>e116c019-a12c-4cf9-9572-fade3be52110</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='management-ajudan-depo']</value>
      <webElementGuid>b53ddaa8-9062-4b7b-8518-06e10ca89bf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manajemen Ajudan'])[1]/following::a[1]</value>
      <webElementGuid>d5872755-4e2a-410c-86e9-8108b7c2c585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Program'])[1]/following::a[2]</value>
      <webElementGuid>9c1fd411-ab5e-4c39-a6b4-b92389c3a158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disetujui'])[12]/preceding::a[1]</value>
      <webElementGuid>69888e9d-e609-4b1c-9749-3c67b8781863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/div/app-sublevel-menu/ul/li/a</value>
      <webElementGuid>7bc528ab-cc98-40aa-a142-2592160f625e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'management-ajudan-depo' and (text() = 'Depo' or . = 'Depo')]</value>
      <webElementGuid>a25ae997-8550-4bc2-b29b-df62d49b5a6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
