<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Disetujui</name>
   <tag></tag>
   <elementGuidId>553513cf-5bc0-40e6-a4fb-abf683a9f8b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#management-ajudan-depo-approved</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='management-ajudan-depo-approved']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>283159ca-6760-4b42-a0a0-22a18a48fdbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlinkactive</name>
      <type>Main</type>
      <value>active-sublevel active-img</value>
      <webElementGuid>9826f621-a7c3-4e27-b7fd-7cfeb3f97e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sublevel-nav-link ng-tns-c115-68 ng-star-inserted</value>
      <webElementGuid>70221d3f-4fcf-43c2-b222-8638be961849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link-active</name>
      <type>Main</type>
      <value>active-sublevel active-img</value>
      <webElementGuid>3d70ccc5-a59d-416b-8ae7-81abc754ecb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>management-ajudan-depo-approved</value>
      <webElementGuid>2b178559-9cbf-4bda-99c9-b39d96a7a850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link</name>
      <type>Main</type>
      <value>merchant/ajudan-management/dep</value>
      <webElementGuid>21172f47-61be-444e-adcd-6c04a43d1195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link-active-options</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>5f5b36ee-136a-4c6e-95bd-f7b3ae0f6c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/web-backoffice/home/merchant/ajudan-management/depo/list</value>
      <webElementGuid>52aae4c7-d31c-4c1d-985c-736c3b18794d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Disetujui</value>
      <webElementGuid>873de624-284d-49f1-a3f8-d4847d8e4ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;management-ajudan-depo-approved&quot;)</value>
      <webElementGuid>870c017b-4f5f-43a1-af15-b79b616a1a6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='management-ajudan-depo-approved']</value>
      <webElementGuid>bd670f6b-eea8-4974-92a9-2c859afb1a1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Depo'])[1]/following::a[1]</value>
      <webElementGuid>67d9951a-7e54-4d00-bf6f-51b1564f1187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manajemen Ajudan'])[1]/following::a[2]</value>
      <webElementGuid>cd2d9959-0562-40c9-a46d-4b4dbb1857ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menunggu Persetujuan'])[12]/preceding::a[1]</value>
      <webElementGuid>b5fff422-f70a-4893-99b1-16c74af92c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/web-backoffice/home/merchant/ajudan-management/depo/list')]</value>
      <webElementGuid>a115f8e1-8278-4ddf-b020-74d7e05c6147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/div/app-sublevel-menu/ul/li/div/app-sublevel-menu/ul/li/span/a</value>
      <webElementGuid>9ec3df43-5a37-42a3-a178-a01819856862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'management-ajudan-depo-approved' and @href = '#/web-backoffice/home/merchant/ajudan-management/depo/list' and (text() = 'Disetujui' or . = 'Disetujui')]</value>
      <webElementGuid>37adc5c4-8450-4749-baa9-bba9996380f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
