<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih File</name>
   <tag></tag>
   <elementGuidId>c9c58c54-f30f-4dac-a4cb-1d93deb4191c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.p-ripple.p-element.align-self-end.p-button-raised.p-button-outlined.p-button-secondary.border-bluegray-100.border-round-lg.p-button-sm.flex-1.p-button.p-component.p-fileupload-choose</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p-fileupload[@id='upload-depo']/div/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e0defa96-ee30-4af6-8bc9-e4c40ef4cab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>df1ee098-a9eb-433a-9dea-922c510fd78e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-element align-self-end p-button-raised p-button-outlined p-button-secondary border-bluegray-100 border-round-lg p-button-sm flex-1 p-button p-component p-fileupload-choose</value>
      <webElementGuid>4ce26e16-d267-4a09-89f5-0484829d59c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>6f878344-27ca-4768-b53b-48ae37fecc22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih File</value>
      <webElementGuid>75c3a7f3-3317-45bd-be39-aadecf0c25ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;upload-depo&quot;)/div[@class=&quot;p-fileupload p-fileupload-basic p-component ng-star-inserted&quot;]/span[@class=&quot;p-ripple p-element align-self-end p-button-raised p-button-outlined p-button-secondary border-bluegray-100 border-round-lg p-button-sm flex-1 p-button p-component p-fileupload-choose&quot;]</value>
      <webElementGuid>42fe16a0-37a3-4dc1-9966-4f7774f9a2d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-fileupload[@id='upload-depo']/div/span</value>
      <webElementGuid>e04a66ba-0974-443e-9de4-31dd2c76e382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload file csv'])[1]/following::span[2]</value>
      <webElementGuid>d1c08cae-b656-49b7-b982-54da4ee16fa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Data'])[2]/following::span[2]</value>
      <webElementGuid>5ec1ad03-85d7-4696-a0c7-55d1973f7bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-fileupload/div/span</value>
      <webElementGuid>b31f0670-eacd-4e9a-a6aa-70f2cd03096e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Pilih File' or . = 'Pilih File')]</value>
      <webElementGuid>e49bdcd7-187c-44c8-891c-9bf2dfcf95dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
